version: '3.8'
services:
  mongodb_container:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017